name: clone
on: 
  workflow_dispatch:   
jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: Create Initial Deployment
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
              touch ~/.ssh/known_hosts
              ssh-keyscan -H github.com >> ~/.ssh/known_hosts
              git clone git@github.com:vrundajasani/cmsc389T-web-template.git
