name: clone
on: 
  workflow_dispatch:   
jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: Create Initial Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
              cd /pub/${{secrets.USERNAME}}
              git clone https://github.com:vrundajasani/cmsc389T-web-template.git
